In [3]:
import pandas as pd

# Ruta al archivo Excel
archivo_excel = "/Users/sebasastre/Downloads/LGBT characters/20220601-LGBTQ-cartoons-series-information-v3.xlsx"

# Leer el archivo Excel
datos_excel = pd.read_excel(archivo_excel, header=1)

# Especifica la ruta del archivo CSV
file_path = '/Users/sebasastre/Downloads/LGBT characters/20220601-LGBTQ-character-demographics-v3.csv'

# Lee el archivo CSV y carga su contenido en un DataFrame de Pandas
df = pd.read_csv(file_path)

# Fusionar los DataFrames
merged_df = pd.merge(datos_excel, df, on='ID', how='inner')

# Mostrar el DataFrame fusionado
merged_df

,ID,show_title_x,TV_rating,IMDB_total_votes,IMDB_rating,seasons,total_episodes,start_date,end_date,duration,...,Unnamed: 19,Unnamed: 20,show_title_y,confirmation_date,character_name,race,gender,orientation,role,representation
0,tt5957358,Freedom Fighters: The Ray,TV-MA,1064,5.8,2,12,12/8/2017,7/18/2018,222,...,NaN,NaN,Freedom Fighters: The Ray,12/8/2017,John Trujillo/Black Condor,POC,Cis Man,Gay,Main Character,Implicit
1,tt5957358,Freedom Fighters: The Ray,TV-MA,1064,5.8,2,12,12/8/2017,7/18/2018,222,...,NaN,NaN,Freedom Fighters: The Ray,12/8/2017,Jacob,White,Cis Man,Gay,Recurring Character,Explicit
2,tt5957358,Freedom Fighters: The Ray,TV-MA,1064,5.8,2,12,12/8/2017,7/18/2018,222,...,NaN,NaN,Freedom Fighters: The Ray,12/8/2017,Ray Terrill/The Ray,White,Cis Man,Gay,Main Character,Explicit
3,tt11237954,Loafy,TV-MA,69,6.7,1,8,8/8/2020,9/5/2020,28,...,NaN,NaN,Loafy,8/8/2020,Scrooge,NaN,Cis Man,Gay,Recurring Character,Explicit
4,tt11237954,Loafy,TV-MA,69,6.7,1,8,8/8/2020,9/5/2020,28,...,NaN,NaN,Loafy,8/8/2020,Eli,NaN,Cis Man,Gay,Recurring Character,Explicit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,tt5580664,Voltron: Legendary Defender,TV-Y7,8504,8.0,8,78,6/10/2016,12/14/2018,917,...,NaN,NaN,Voltron: Legendary Defender,6/10/2016,Curtis,POC,Cis Man,Gay,Guest Character,Explicit
349,tt5580664,Voltron: Legendary Defender,TV-Y7,8504,8.0,8,78,6/10/2016,12/14/2018,917,...,NaN,NaN,Voltron: Legendary Defender,6/10/2016,Adam,POC,Cis Man,Gay,Main Character,Explicit
350,tt0383718,W.I.T.C.H.,TV-Y7,3463,7.3,2,52,12/18/2004,12/23/2006,735,...,NaN,NaN,W.I.T.C.H.,12/18/2004,Irma Lair,White,Cis Woman,Lesbian,Main Character,Implicit
351,tt0383718,W.I.T.C.H.,TV-Y7,3463,7.3,2,52,12/18/2004,12/23/2006,735,...,NaN,NaN,W.I.T.C.H.,2/12/2005,Nerissa,White,Cis Woman,Bisexual,Recurring Character,Implicit
352,tt0383718,W.I.T.C.H.,TV-Y7,3463,7.3,2,52,12/18/2004,12/23/2006,735,...,NaN,NaN,W.I.T.C.H.,8/21/2006,Cassidy,White,Cis Woman,Lesbian,Recurring Character,Implicit

In [4]:
# Contar el número de filas con el valor "Cis Man" en la columna "gender"
count_cis_man = df['gender'].value_counts()['Cis Man']

print("Número de filas con 'Cis Man' en la columna 'gender':", count_cis_man)

Número de filas con 'Cis Man' en la columna 'gender': 168

In [5]:
# Contar la cantidad de cada valor único en la columna "gender"
gender_counts = df['gender'].value_counts()

print("Cantidad de cada valor único en la columna 'gender':")
print(gender_counts)

Cantidad de cada valor único en la columna 'gender':
Cis Man         168
Cis Woman       131
Non Binary       20
Trans Woman      16
Agender           6
Genderfluid       5
Undetermined      3
Trans Man         3
Intersex          1
Name: gender, dtype: int64

In [6]:
# Obtener todas las categorías distintas de la columna "orientation" y contar la cantidad de cada una
orientation_counts = df['orientation'].value_counts()

# Imprimir las categorías únicas en la columna 'orientation' junto con su cantidad
print("Categorías únicas en la columna 'orientation' y su cantidad:")
print(orientation_counts)

Categorías únicas en la columna 'orientation' y su cantidad:
Gay             121
Lesbian          82
Undetermined     59
Bisexual         52
Queer            18
Pansexual        11
Asexual           6
Polyamorous       2
Ambiguous         1
Straight          1
Name: orientation, dtype: int64

In [7]:
# Agrupar por la columna "network" y contar la cantidad de personajes únicos en cada una
network_characters_counts = merged_df.groupby('network')['character_name'].nunique()

# Ordenar los resultados en orden descendente según la cantidad de personajes
network_characters_counts_sorted = network_characters_counts.sort_values(ascending=False)

# Mostrar las redes distintas y la cantidad de personajes únicos en cada una, ordenadas de mayor a menor
print("Redes distintas y cantidad de personajes únicos en cada una, ordenadas de mayor a menor:")
print(network_characters_counts_sorted)

Redes distintas y cantidad de personajes únicos en cada una, ordenadas de mayor a menor:
network
Netflix                  86
Cartoon Network          58
Fox                      32
Comedy Central           18
Nickelodeon              17
Adult Swim               16
Disney Channel           14
YouTube                  13
HBO Max                  10
Hulu                     10
ABC                       8
Rooster Teeth             8
Showtime                  7
Amazon Prime              7
Crunchyroll Originals     6
The Hub                   6
FX Networks               5
Paramount +               5
LOGO TV                   4
The WB                    4
Disney XD                 4
ABC Kids                  3
CW Seed                   3
Disney Junior             2
Web Series                2
Kids' WB                  1
Myx TV                    1
PBS                       1
SyFy                      1
Name: character_name, dtype: int64

In [8]:
# Primero, eliminamos duplicados de personajes en diferentes shows
unique_characters = merged_df.drop_duplicates(subset=['character_name', 'show_title_y'])

# Luego, agrupamos por 'show_title' y contamos la cantidad de personajes únicos
show_characters_counts = unique_characters.groupby('show_title_y').size()

# Ordenamos los resultados en orden descendente según la cantidad de personajes únicos
show_characters_counts_sorted = show_characters_counts.sort_values(ascending=False)

# Seleccionamos los primeros 20 resultados
top_20_show_titles = show_characters_counts_sorted.head(20)

# Mostramos los resultados
print("Los 20 show_title con la mayor cantidad de character_name indistintos:")
print(top_20_show_titles)

Los 20 show_title con la mayor cantidad de character_name indistintos:
show_title_y
She-Ra and the Princesses of Power     19
Steven Universe                        11
South Park                             10
Craig of the Creek                      9
OK K.O.! Let's Be Heroes                9
Q-Force                                 8
Big Mouth                               8
The Loud House                          7
Family Guy                              7
Queer Duck                              7
Young Justice                           7
BoJack Horseman                         7
Summer Camp Island                      6
The Dragon Prince                       5
The Simpsons                            5
RWBY                                    5
My Little Pony: Friendship is Magic     5
The Owl House                           4
The Goode Family                        4
High Guardian Spice                     4
dtype: int64

In [10]:
# Agrupar por la columna "network" y contar la cantidad de títulos de espectáculos únicos
show_titles_by_network = merged_df.groupby('network')['show_title_x'].nunique()

# Mostrar los resultados
print("Cantidad de títulos de shows únicos por Network:")
print(show_titles_by_network)

Cantidad de títulos de shows únicos por Network:
network
ABC                       2
ABC Kids                  1
Adult Swim                7
Amazon Prime              3
CW Seed                   1
Cartoon Network          14
Comedy Central            5
Crunchyroll Originals     2
Disney Channel            6
Disney Junior             1
Disney XD                 2
FX Networks               2
Fox                      11
HBO Max                   4
Hulu                      5
Kids' WB                  1
LOGO TV                   1
Myx TV                    1
Netflix                  22
Nickelodeon               6
PBS                       1
Paramount +               3
Rooster Teeth             3
Showtime                  1
SyFy                      1
The Hub                   2
The WB                    3
Web Series                1
YouTube                   6
Name: show_title_x, dtype: int64

In [11]:
# Filtrar el DataFrame combinado por el título del espectáculo
she_ra_df = merged_df[merged_df['show_title_x'] == 'She-Ra and the Princesses of Power']

# Seleccionar las columnas relevantes
she_ra_characters_info = she_ra_df[['character_name', 'race', 'orientation', 'gender']]

# Mostrar los resultados
print("Información de personajes de She-Ra and the Princesses of Power:")
print(she_ra_characters_info)

Información de personajes de She-Ra and the Princesses of Power:
     character_name   race orientation      gender
287          George    POC         Gay     Cis Man
288            Kyle  White         Gay     Cis Man
289           Lance    POC         Gay     Cis Man
290             Bow    POC    Bisexual     Cis Man
291         Rogelio    NaN         Gay     Cis Man
292        Sea Hawk  White       Queer     Cis Man
293          Falcon  White       Queer     Cis Man
294         Scorpia    POC     Lesbian   Cis Woman
295         Netossa    POC     Lesbian   Cis Woman
296           Catra    POC     Lesbian   Cis Woman
297           Adora  White     Lesbian   Cis Woman
298        Entrapta    POC   Pansexual   Cis Woman
299            Mara    POC       Queer   Cis Woman
300     Spinnerella  White     Lesbian   Cis Woman
301         Huntara    NaN     Lesbian   Cis Woman
302         Glimmer    POC    Bisexual   Cis Woman
303         Perfuma    POC    Bisexual   Cis Woman
304      Light Hope    NaN       Queer   Cis Woman
305  Double Trouble    NaN       Queer  Non Binary

In [12]:
# Filtrar el DataFrame combinado por el rol "Main Character"
main_characters_df = merged_df[merged_df['role'] == 'Main Character']

# Mostrar los resultados
print("Personajes cuyo rol es Main Character:")
main_characters_df

Personajes cuyo rol es Main Character:

,ID,show_title_x,TV_rating,IMDB_total_votes,IMDB_rating,seasons,total_episodes,start_date,end_date,duration,...,Unnamed: 19,Unnamed: 20,show_title_y,confirmation_date,character_name,race,gender,orientation,role,representation
0,tt5957358,Freedom Fighters: The Ray,TV-MA,1064,5.8,2,12,12/8/2017,7/18/2018,222,...,NaN,NaN,Freedom Fighters: The Ray,12/8/2017,John Trujillo/Black Condor,POC,Cis Man,Gay,Main Character,Implicit
2,tt5957358,Freedom Fighters: The Ray,TV-MA,1064,5.8,2,12,12/8/2017,7/18/2018,222,...,NaN,NaN,Freedom Fighters: The Ray,12/8/2017,Ray Terrill/The Ray,White,Cis Man,Gay,Main Character,Explicit
5,tt8011944,Nomad of Nowhere,TV-G,347,7.3,1,12,3/16/2018,9/21/2018,189,...,NaN,NaN,Nomad of Nowhere,3/16/2018,Skout,White,Cis Woman,Lesbian,Main Character,Implicit
8,tt10394790,The Bravest Knight,TV-Y,109,6.3,1,13,6/21/2019,10/11/2019,112,...,NaN,NaN,The Bravest Knight,6/21/2019,Sir Cedric,White,Cis Man,Gay,Main Character,Explicit
17,tt0397306,American Dad!,TV-14,123144,7.3,19,322,2/6/2005,NaN,6201,...,NaN,NaN,American Dad!,2/6/2005,Roger,NaN,Agender,Pansexual,Main Character,Explicit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,tt0291672,Time Squad,TV-Y7,1586,7.4,2,26,6/8/2001,11/26/2003,901,...,NaN,NaN,Time Squad,6/8/2001,Larry 3000,NaN,Cis Man,Gay,Main Character,Implicit
345,tt8009622,Twelve Forever,TV-Y7,643,6.4,1,25,7/29/2019,7/29/2019,0,...,NaN,NaN,Twelve Forever,7/29/2019,Reggie Abbott,White,Cis Woman,Queer,Main Character,Explicit
347,tt5580664,Voltron: Legendary Defender,TV-Y7,8504,8.0,8,78,6/10/2016,12/14/2018,917,...,NaN,NaN,Voltron: Legendary Defender,6/10/2016,Takashi Shirogane,POC,Cis Man,Gay,Main Character,Explicit
349,tt5580664,Voltron: Legendary Defender,TV-Y7,8504,8.0,8,78,6/10/2016,12/14/2018,917,...,NaN,NaN,Voltron: Legendary Defender,6/10/2016,Adam,POC,Cis Man,Gay,Main Character,Explicit
350,tt0383718,W.I.T.C.H.,TV-Y7,3463,7.3,2,52,12/18/2004,12/23/2006,735,...,NaN,NaN,W.I.T.C.H.,12/18/2004,Irma Lair,White,Cis Woman,Lesbian,Main Character,Implicit

In [15]:
# Filtrar el DataFrame combinado por el rol "Main Character"
main_characters_df = merged_df[merged_df['role'] == 'Main Character']

# Obtener una lista de los personajes únicos cuyo rol es "Main Character"
main_characters_list = main_characters_df['character_name'].unique()

# Mostrar la lista de personajes
print("Personajes cuyo rol es Main Character:")
print(main_characters_list)

Personajes cuyo rol es Main Character:
['John Trujillo/Black Condor' 'Ray Terrill/The Ray' 'Skout' 'Sir Cedric'
 'Roger' 'Caitlyn Kiramman' 'Vi' 'Queen Bean' 'Mia Abara' 'Stewie Griffin'
 'Meg Griffin' 'Yung Hee Tyson' 'Adam Seymour Duckstein'
 'Steven Arlo Gator' 'Melissa Duckstein' 'Zip Danger/Frantic' 'Ham Tobin'
 'D.D. Danger' 'Ray Gillette' 'Pam Poovey' 'Jay Bilzerian' 'Jessi Glaser'
 'Todd Chavez' 'Connie Cunaman' 'Alucard' 'Daniel' 'Chozen' 'Hunter'
 'Fymrym' 'Xandir P. Whifflebottom' 'Ling-Ling' 'Captain Leslie Hero'
 'Foxxy Love' 'Eileen Murphy' 'Log Cabin Republican' 'Clayface'
 'Harley Quinn' 'Poison Ivy' 'Alastor' 'Angel Dust' 'Vaggie'
 'Charlie Magne' 'Blitzo' 'Moxxie' 'Snapdragon' 'Scott' 'Daisy'
 'Gary Garoldson' 'Melissa Tartleton' 'Steve Maryweather' 'Rick Brocka'
 'Steve' 'Dana Bernstein' 'Kirsten Kellogg' 'Jingle Jim' 'Goldie' 'Korvo'
 'Herbert Garrison' 'Beckett Mariner' 'Alice' 'Colonel Horace Gentleman'
 'Tuca' 'Plum' 'Thomas' 'Valentina Romanyszyn' 'Blake Belladonna' 'Korra'
 'Waylon Smithers' "Kaldur'ahm" 'Fred' 'SpongeBob' 'Zulius' 'Ched'
 'Kelsey Pokoly' 'Owen Burnett' 'Benson Mekler' 'Enid' 'Radicles'
 'Velma Dinkley' 'Bow' 'Catra' 'Adora' 'Glimmer' 'Zero' 'Richie Foley'
 'Eda Clawthorne' 'Luz Noceda' 'Ren' 'Stimpy' 'Larry 3000' 'Reggie Abbott'
 'Takashi Shirogane' 'Adam' 'Irma Lair']

In [16]:
# Contar la cantidad de personajes cuyo rol es "Main Character"
cantidad_main_characters = len(main_characters_list)

# Mostrar la cantidad de personajes
print("Cantidad de personajes cuyo rol es Main Character:", cantidad_main_characters)

Cantidad de personajes cuyo rol es Main Character: 94

In [17]:
# Contar la cantidad de shows distintos en la columna 'show_title_x'
cantidad_de_shows = merged_df['show_title_x'].nunique()

# Mostrar la cantidad de shows distintos
print("Cantidad de shows distintos:", cantidad_de_shows)

Cantidad de shows distintos: 118

In [18]:
# Obtener las categorías únicas de la columna 'role'
categorias_role = merged_df['role'].unique()

# Mostrar las categorías únicas
print("Categorías de la columna 'role':")
print(categorias_role)

Categorías de la columna 'role':
['Main Character' 'Recurring Character' 'Supporting Character'
 'Guest Character']

In [19]:
# Contar la cantidad de cada categoría en la columna 'role'
role_counts = merged_df['role'].value_counts()

# Mostrar los resultados
print("Cantidad de cada categoría en la columna 'role':")
print(role_counts)

Cantidad de cada categoría en la columna 'role':
Recurring Character     175
Main Character           95
Supporting Character     44
Guest Character          39
Name: role, dtype: int64

In [20]:
# Counting the number of unique character names
character_count = merged_df['character_name'].nunique()

# Printing the count of unique character names
print("Cantidad de nombres de personajes únicos:", character_count)

Cantidad de nombres de personajes únicos: 348

In [21]:
# Convert 'start_date' column to datetime
merged_df['start_date'] = pd.to_datetime(merged_df['start_date'])

# Extract year from 'start_date' column
merged_df['year'] = merged_df['start_date'].dt.year

# Count the number of shows per year
shows_per_year = merged_df.groupby('year')['show_title_x'].nunique()

# Print the result
print("Cantidad de shows por año:")
print(shows_per_year)

Cantidad de shows por año:
year
1989     1
1991     1
1994     2
1996     3
1997     2
1999     4
2000     2
2001     2
2003     1
2004     3
2005     3
2006     1
2007     3
2009     4
2010     5
2011     2
2012     6
2013     5
2014     3
2015     2
2016     2
2017     7
2018    12
2019    15
2020    11
2021    16
Name: show_title_x, dtype: int64

In [22]:
# Cuenta la cantidad de shows por cada categoría de rating
rating_counts = merged_df['TV_rating'].value_counts()

# Imprime los resultados
print("Cantidad de shows por categoría de rating:")
rating_counts

Cantidad de shows por categoría de rating:

TV-MA    113
TV-Y7    112
TV-PG     55
TV-14     44
TV-Y      19
TV-G      10
Name: TV_rating, dtype: int64